#!/bin/bash

cd firmware

# This is generated by ffc_build.sh. May need to update version here to match the
# generated file.
hex_file="./build/ff_creator-2560$ ls ff_creator-2560_v7.8.0.en.hex"

serial_port="/dev/tty.usbmodemFA131"

avrdude_dir="/Applications/ReplicatorG.app/Contents/Resources/tools"

${avrdude_dir}/avrdude \
  -v -v \
  -D -F -V \
  -C ${avrdude_dir}/avrdude.conf  \
  -p atmega2560 \
  -P ${serial_port} \
  -c stk500v2 \
  -b 57600 \
  -U flash:w:build/ff_creator-2560/ff_creator-2560_v7.8.0.en.hex


